# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_bank', '0003_auto_20171011_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(default='hdfc', max_length=100),
            preserve_default=False,
        ),
    ]
